name = "heimdall"
compatibility_date = "2024-09-19"
compatibility_flags = [ "nodejs_compat" ]

[env.dev]
[[env.dev.r2_buckets]]
binding = "HEIMDALL_BUCKET"
bucket_name = "heimdall-dev"

[env.prod]
[[env.prod.r2_buckets]]
binding = "HEIMDALL_BUCKET"
bucket_name = "heimdall-prod"

