name = "heimdall-api"
compatibility_date = "2024-09-19"
compatibility_flags = [ "nodejs_compat_v2" ]
main = "src/index.ts" 


[[r2_buckets]]
binding = "HEIMDALL_BUCKET"
bucket_name = "heimdall-dev"

[env.dev]
routes = [
	{ pattern = "api.dev.heimdall.rockyshoreslabs.io", custom_domain = true },
]

[[env.dev.r2_buckets]]
binding = "HEIMDALL_BUCKET"
bucket_name = "heimdall-dev"



[env.prod]
routes = [
	{ pattern = "api.heimdall.rockyshoreslabs.io", custom_domain = true },
]

[[env.prod.r2_buckets]]
binding = "HEIMDALL_BUCKET"
bucket_name = "heimdall-prod"

